### ISSUE TITLE
This extension does not yet support the current version of JupyterLab

### ISSUE THREAD

**Issue by isConic** [nengo/jupyterlab_nengo#4]
I'm running 

```jupyter labextension install @jgosmann/jupyterlab-nengo```  

I get the following error

```ValueError: This extension does not yet support the current version of JupyterLab.```   

![image](https://user-images.githubusercontent.com/48657113/60366922-ef580280-99ba-11e9-9e4c-bca74d519d0f.png) 
  
**Versions of things:**
```
pip freeze | grep jupyter

jupyter-client==5.2.4
jupyter-core==4.5.0
jupyterlab==1.0.0
jupyterlab-server==1.0.0
```

```
pip freeze | grep nengo

nengo==2.8.0
nengo-gui==0.4.4
```
I'm posting this issue to highlight out of the box-incompatibility with the latest Jupyter Lab version. Im also asking for help getting nengo working with a limited understanding of how jupyter lab extensions work, or how to resolve the mismatch.

**Comment by jgosmann** [comment]
fyi: I won't be able to look into this before the end of July.

**Comment by jgosmann** [comment]
Finally got around to do this. In theory the extension should work again, but requires [a fix in Nengo GUI itself](https://github.com/nengo/nengo-gui/pull/1021).

It is not really under my control when the fix will get merged there and it might take several months from my experience. 😐
